ARM64/dts: sdm670: Correct include order for aqt1000-cdp variant DTBOs
By the order it currently has, node shortcut is called before the node is
actually defined, causing ufdt_apply_overlay to be unable to resolve the
node target.

    DTC     arch/arm64/boot/dts/qcom/sdm670-aqt1000-cdp-overlay.dtbo
    VERIFY  arch/arm64/boot/dts/qcom/sdm670-aqt1000-cdp-overlay.dtbo
  ERROR: ufdt_overlay_get_target():failed to find target 04dc
  ERROR: ufdt_apply_fragment():Unable to resolve target for fragment@10
  ERROR: ufdt_overlay_apply_fragments():failed to apply overlay fragment fragment@10 ret: 4
  ERROR: ufdt_overlay_apply():failed to apply fragments

Resolve this by ensuring sdm670-cdp is included before sdm670-int-cdc-aqt.
For SDM710 with PM660A version, correcting the order isn't really necessary
but let's do to this one anyway.

Signed-off-by: Albert I <kras@raphielgang.org>